//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6JoinExperiment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ef6JoinExperimentEntities : DbContext
    {
        public Ef6JoinExperimentEntities()
            : base("name=Ef6JoinExperimentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classroom> Classrooms { get; set; }
        public virtual DbSet<ClassroomSeat> ClassroomSeats { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Tutor> Tutors { get; set; }
        public virtual DbSet<AssociationMembership> AssociationMemberships { get; set; }
        public virtual DbSet<TutorAssociation> TutorAssociations { get; set; }
    }
}
